# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_polygonarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygonarea',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='polygonarea',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
