# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160429_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='language',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
